### ISSUE TITLE
Logout after minutes of inactivity

### ISSUE THREAD

**Issue by benhaynes** [directus/app#1175]
There have been reports (Slack + email) of being logged out after only a few minutes. I'm adding this here so that we have a single place to monitor this and aggregate logs. Hopefully someone can provide steps to reproduce.

**Comment by rijkvanzanten** [comment]
One explanation for this would be that the token wasn't automatically refreshed. Which means that the /auth/refresh endpoint either errors out, or doesn't exist.

(I haven't been able to reproduce this btw, just throwing in my 2 cents)

**Comment by hellmaca** [comment]
I have been having this error. It does not occur when I am developing locally. It only happens when I deploy the app to PCF using their php buildpack.  I am using a MySQL tile for my db. Another error I am getting in all environments is the inability to change the auto sign out behavior.  I can change the setting but it does not affect the behavior.  I have tried to change multiple settings in the php.ini file to no avail.  I appreciate the help on this issue.

**Comment by hellmaca** [comment]
Here is a copy of the logs when the error occurs:

[2018-12-06 10:54:49] api[_].ERROR: Directus\Authentication\Exception\ExpiredTokenException: Expired token in pathToCMS/directus/src/core/Directus/Util/JWTUtils.php:33
Stack trace:
#0 pathToCMS/directus/src/core/Directus/Authentication/Provider.php(554): Directus\Util\JWTUtils::decode
#1 pathToCMS/directus/src/core/Directus/Authentication/Provider.php(218): Directus\Authentication\Provider->getTokenPayload
#2 pathToCMS/directus/src/core/Directus/Services/AuthService.php(193): Directus\Authentication\Provider->authenticateWithToken
#3 pathToCMS/directus/src/core/Directus/Application/Http/Middleware/AuthenticationMiddleware.php(99): Directus\Services\AuthService->authenticateWithToken
#4 pathToCMS/directus/src/core/Directus/Application/Http/Middleware/AuthenticationMiddleware.php(31): Directus\Application\Http\Middleware\AuthenticationMiddleware->authenticate
#5 [internal function]: Directus\Application\Http\Middleware\AuthenticationMiddleware->__invoke
#6 pathToCMS/directus/vendor/slim/slim/Slim/DeferredCallable.php(43): call_user_func_array
#7 [internal function]: Slim\DeferredCallable->__invoke
#8 pathToCMS/directus/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#9 pathToCMS/directus/src/core/Directus/Application/Http/Middleware/TableGatewayMiddleware.php(25): Slim\Route->Slim\{closure}
#10 [internal function]: Directus\Application\Http\Middleware\TableGatewayMiddleware->__invoke
#11 pathToCMS/directus/vendor/slim/slim/Slim/DeferredCallable.php(43): call_user_func_array
#12 [internal function]: Slim\DeferredCallable->__invoke
#13 pathToCMS/directus/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#14 pathToCMS/directus/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\Route->Slim\{closure}
#15 pathToCMS/directus/vendor/slim/slim/Slim/Route.php(334): Slim\Route->callMiddlewareStack
#16 pathToCMS/directus/vendor/slim/slim/Slim/App.php(515): Slim\Route->run
#17 pathToCMS/directus/src/core/Directus/Application/Http/Middleware/AbstractRateLimitMiddleware.php(34): Slim\App->__invoke
#18 [internal function]: Directus\Application\Http\Middleware\AbstractRateLimitMiddleware->__invoke
#19 pathToCMS/directus/vendor/slim/slim/Slim/DeferredCallable.php(43): call_user_func_array
#20 [internal function]: Slim\DeferredCallable->__invoke
#21 pathToCMS/directus/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#22 pathToCMS/directus/vendor/akrabat/rka-ip-address-middleware/src/IpAddress.php(93): Slim\App->Slim\{closure}
#23 [internal function]: RKA\Middleware\IpAddress->__invoke
#24 pathToCMS/directus/vendor/slim/slim/Slim/DeferredCallable.php(43): call_user_func_array
#25 [internal function]: Slim\DeferredCallable->__invoke
#26 pathToCMS/directus/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#27 pathToCMS/directus/src/core/Directus/Application/Http/Middleware/CorsMiddleware.php(66): Slim\App->Slim\{closure}
#28 [internal function]: Directus\Application\Http\Middleware\CorsMiddleware->__invoke
#29 pathToCMS/directus/vendor/slim/slim/Slim/DeferredCallable.php(43): call_user_func_array
#30 [internal function]: Slim\DeferredCallable->__invoke
#31 pathToCMS/directus/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#32 pathToCMS/directus/src/core/Directus/Application/Http/Middleware/ResponseCacheMiddleware.php(47): Slim\App->Slim\{closure}
#33 [internal function]: Directus\Application\Http\Middleware\ResponseCacheMiddleware->__invoke
#34 pathToCMS/directus/vendor/slim/slim/Slim/DeferredCallable.php(43): call_user_func_array
#35 [internal function]: Slim\DeferredCallable->__invoke
#36 pathToCMS/directus/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#37 pathToCMS/directus/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\App->Slim\{closure}
#38 pathToCMS/directus/vendor/slim/slim/Slim/App.php(406): Slim\App->callMiddlewareStack
#39 pathToCMS/directus/vendor/slim/slim/Slim/App.php(314): Slim\App->process
#40 pathToCMS/directus/src/core/Directus/Application/Application.php(161): Slim\App->run
#41 pathToCMS/directus/public/index.php(5): Directus\Application\Application->run [] []

**Comment by hellmaca** [comment]
I don't know if this information is helpful, but comparing the response headers between localhost and the dev environment I see a few differences. Localhost has these values that the dev environment does not:

- Connection: Keep-Alive
- Keep-Alive: timeout=5, max=100

I do not think this matters, but honestly I have no clue what is going on.

**Comment by makote** [comment]
This is also happening to me, but it happens with or without activity. Even while capturing data or creating new collections.

**Comment by hellmaca** [comment]
@makote I am experiencing that behavior as well.The JWT token expires. According to the docs, credentials are supposed to be forwarded to the SDK.  I am using the directus suite v 7.0.11.

**Comment by hellmaca** [comment]
I went through [this process](https://docs.bolt.cm/3.6/howto/making-sure-htaccess-works) process to see if the rewrite module was enabled which it was.  After some testing I think this is happening server side.  The browser sends the same cookies during a session but I see 401 errors from the server. Still working on solving this issue.

**Comment by benhaynes** [comment]
Thanks for the info @hellmaca!

@rijkvanzanten @WellingGuzman — any thoughts on this? If it is an API issue I can transfer...

**Comment by rijkvanzanten** [comment]
Is there any errors visible in the logs folder in the API?

It's either a problem with reading the token correctly (invalid signature) or the application sends the token too late, which would explain this too, but would be weird seeing that it only happens on certain server setups. (The app is purely client side so that shouldn't cause any issue)

**Comment by makote** [comment]
### Here is the API Log for one such event:

`[2018-12-11 10:28:37] api[_].ERROR: Directus\Authentication\Exception\ExpiredTokenException: Expired token in .../src/core/Directus/Util/JWTUtils.php:33
Stack trace:
#0 .../src/core/Directus/Authentication/Provider.php(554): Directus\Util\JWTUtils::decode
#1 .../src/core/Directus/Authentication/Provider.php(440): Directus\Authentication\Provider->getTokenPayload
#2 .../src/core/Directus/Services/AuthService.php(385): Directus\Authentication\Provider->refreshToken
#3 .../src/endpoints/Auth.php(118): Directus\Services\AuthService->refreshToken
#4 [internal function]: Directus\Api\Routes\Auth->refresh
#5 .../vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(41): call_user_func
#6 .../vendor/slim/slim/Slim/Route.php(356): Slim\Handlers\Strategies\RequestResponse->__invoke
#7 .../src/core/Directus/Application/Http/Middleware/TableGatewayMiddleware.php(25): Slim\Route->__invoke
#8 [internal function]: Directus\Application\Http\Middleware\TableGatewayMiddleware->__invoke
#9 .../vendor/slim/slim/Slim/DeferredCallable.php(43): call_user_func_array
#10 [internal function]: Slim\DeferredCallable->__invoke
#11 .../vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#12 .../vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\Route->Slim\{closure}
#13 .../vendor/slim/slim/Slim/Route.php(334): Slim\Route->callMiddlewareStack
#14 .../vendor/slim/slim/Slim/App.php(515): Slim\Route->run
#15 .../src/core/Directus/Application/Http/Middleware/AbstractRateLimitMiddleware.php(34): Slim\App->__invoke
#16 [internal function]: Directus\Application\Http\Middleware\AbstractRateLimitMiddleware->__invoke
#17 .../vendor/slim/slim/Slim/DeferredCallable.php(43): call_user_func_array
#18 [internal function]: Slim\DeferredCallable->__invoke
#19 .../vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#20 .../vendor/akrabat/rka-ip-address-middleware/src/IpAddress.php(93): Slim\App->Slim\{closure}
#21 [internal function]: RKA\Middleware\IpAddress->__invoke
#22 .../vendor/slim/slim/Slim/DeferredCallable.php(43): call_user_func_array
#23 [internal function]: Slim\DeferredCallable->__invoke
#24 .../vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#25 .../src/core/Directus/Application/Http/Middleware/CorsMiddleware.php(66): Slim\App->Slim\{closure}
#26 [internal function]: Directus\Application\Http\Middleware\CorsMiddleware->__invoke
#27 .../vendor/slim/slim/Slim/DeferredCallable.php(43): call_user_func_array
#28 [internal function]: Slim\DeferredCallable->__invoke
#29 .../vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#30 .../src/core/Directus/Application/Http/Middleware/ResponseCacheMiddleware.php(47): Slim\App->Slim\{closure}
#31 [internal function]: Directus\Application\Http\Middleware\ResponseCacheMiddleware->__invoke
#32 .../vendor/slim/slim/Slim/DeferredCallable.php(43): call_user_func_array
#33 [internal function]: Slim\DeferredCallable->__invoke
#34 .../vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#35 .../vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\App->Slim\{closure}
#36 .../vendor/slim/slim/Slim/App.php(406): Slim\App->callMiddlewareStack
#37 .../vendor/slim/slim/Slim/App.php(314): Slim\App->process
#38 .../src/core/Directus/Application/Application.php(161): Slim\App->run
#39 .../public/index.php(5): Directus\Application\Application->run [] []`

**Comment by benhaynes** [comment]
This was mentioned on Slack:

> the token gets invalid after a couple of seconds, i searched a bit and in the past there was problems on token expiration in reason of the set timezone of php.ini, do you think this could be related?

**Comment by hellmaca** [comment]
Could it have anything to do with time? My laptop is blocked from automatically updating the time because it is on a corporate network.  My work laptop clock is consistently behind my phone and watch.  Could this discrepancy be the cause of the issue?

**Comment by verbman** [comment]
I also have this issue, I decoded the jwt token and it's expiry was about 4-5 minutes from issue. I've got around it by raising the frequency of my refresh token requests - but in a dev environment those refresh requests get knocked about a lot so it still impacts.

**Comment by rijkvanzanten** [comment]
> Could it have anything to do with time? My laptop is blocked from automatically updating the time because it is on a corporate network. My work laptop clock is consistently behind my phone and watch. Could a discrepancy between the clock on the laptop and the server clock be the cause of the issue?

!! Wow. If the server time is minutes ahead of the client, then we'll see problems in the token, as it's thinks the token hasn't expired yet when it has 😬

(Time zones are corrected for so that's not the problem)

**Comment by rijkvanzanten** [comment]
I think I have a fix in mind. We know the expiry time of the token when we get it (now + n minutes) so instead of checking against the time in the token (server time) we could store the "wrong time corrected" expiry time in a variable and use that in the check instead. That should take care of the 'wrong time on the computer issue' I think 🤔

**Comment by hellmaca** [comment]
I manually updated the time on my laptop.  I no longer experience the log out after 5 minutes issue.  This would also explain why expected behavior has always been happening locally since my server clock is my laptop clock.

**Comment by rijkvanzanten** [comment]
@makote @verbman could this be the cause for you as well? Could you confirm the date time settings on the platform where this is happening?

**Comment by makote** [comment]
I can confirm there is an offset of about 30 secs between my server time and the client time. Will do a test later.

**Comment by anelad** [comment]
Mhppss, I'm still having the issue I suppose. I've set the "Auto Sign out option" to 60 but the system kicks me out sometimes in 30 secs, sometimes 3 mins.
