### ISSUE TITLE
Issue modifying length of Decimal field

### ISSUE THREAD

**Issue by shinroo** [directus/app#2750]
We have a few decimal fields on various collections, which were initially at length `10,0`. We'd like these to be changed to `10,6` but this does not always work as Directus sometimes raises an error message:
<img width="382" alt="Screenshot 2020-04-21 at 11 46 57" src="https://user-images.githubusercontent.com/15915453/79878429-b2e41000-83ed-11ea-80a9-d224f5109637.png">
Checking the logs we see the following error trace:
```
[2020-04-21 09:46:55] api[_].ERROR: Directus\Exception\SQLException: SQLSTATE[22003]: Numeric value out of range: 1264 Out of range value for column 'actuals_usd_period__ex_admin' at row 8 in /var/directus/src/endpoints/Fields.php:122
Stack trace:
#0 [internal function]: Directus\Api\Routes\Fields->update
#1 /var/directus/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(40): call_user_func
#2 /var/directus/vendor/slim/slim/Slim/Route.php(281): Slim\Handlers\Strategies\RequestResponse->__invoke
#3 /var/directus/src/core/Directus/Application/Http/Middleware/AbstractRateLimitMiddleware.php(34): Slim\Route->__invoke
#4 [internal function]: Directus\Application\Http\Middleware\AbstractRateLimitMiddleware->__invoke
#5 /var/directus/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array
#6 [internal function]: Slim\DeferredCallable->__invoke
#7 /var/directus/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#8 /var/directus/src/core/Directus/Application/Http/Middleware/AuthenticationMiddleware.php(124): Slim\Route->Slim\{closure}
#9 [internal function]: Directus\Application\Http\Middleware\AuthenticationMiddleware->__invoke
#10 /var/directus/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array
#11 [internal function]: Slim\DeferredCallable->__invoke
#12 /var/directus/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#13 /var/directus/src/core/Directus/Application/Http/Middleware/TableGatewayMiddleware.php(25): Slim\Route->Slim\{closure}
#14 [internal function]: Directus\Application\Http\Middleware\TableGatewayMiddleware->__invoke
#15 /var/directus/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array
#16 [internal function]: Slim\DeferredCallable->__invoke
#17 /var/directus/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#18 /var/directus/src/core/Directus/Application/Http/Middleware/DatabaseMigrationMiddleware.php(15): Slim\Route->Slim\{closure}
#19 [internal function]: Directus\Application\Http\Middleware\DatabaseMigrationMiddleware->__invoke
#20 /var/directus/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array
#21 [internal function]: Slim\DeferredCallable->__invoke
#22 /var/directus/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#23 /var/directus/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\Route->Slim\{closure}
#24 /var/directus/vendor/slim/slim/Slim/Route.php(268): Slim\Route->callMiddlewareStack
#25 /var/directus/vendor/slim/slim/Slim/App.php(503): Slim\Route->run
#26 /var/directus/src/core/Directus/Application/Http/Middleware/AbstractRateLimitMiddleware.php(34): Slim\App->__invoke
#27 [internal function]: Directus\Application\Http\Middleware\AbstractRateLimitMiddleware->__invoke
#28 /var/directus/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array
#29 [internal function]: Slim\DeferredCallable->__invoke
#30 /var/directus/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#31 /var/directus/vendor/directus/proxy-detection/src/ProxyDetectionMiddleware.php(30): Slim\App->Slim\{closure}
#32 /var/directus/src/core/Directus/Application/Http/Middleware/ProxyMiddleware.php(18): RKA\Middleware\ProxyDetectionMiddleware->__invoke
#33 [internal function]: Directus\Application\Http\Middleware\ProxyMiddleware->__invoke
#34 /var/directus/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array
#35 [internal function]: Slim\DeferredCallable->__invoke
#36 /var/directus/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#37 /var/directus/vendor/akrabat/ip-address-middleware/src/IpAddress.php(113): Slim\App->Slim\{closure}
#38 [internal function]: RKA\Middleware\IpAddress->__invoke
#39 /var/directus/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array
#40 [internal function]: Slim\DeferredCallable->__invoke
#41 /var/directus/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#42 /var/directus/src/core/Directus/Application/Http/Middleware/CorsMiddleware.php(71): Slim\App->Slim\{closure}
#43 [internal function]: Directus\Application\Http\Middleware\CorsMiddleware->__invoke
#44 /var/directus/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array
#45 [internal function]: Slim\DeferredCallable->__invoke
#46 /var/directus/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#47 /var/directus/src/core/Directus/Application/Http/Middleware/ResponseCacheMiddleware.php(63): Slim\App->Slim\{closure}
#48 [internal function]: Directus\Application\Http\Middleware\ResponseCacheMiddleware->__invoke
#49 /var/directus/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array
#50 [internal function]: Slim\DeferredCallable->__invoke
#51 /var/directus/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#52 /var/directus/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\App->Slim\{closure}
#53 /var/directus/vendor/slim/slim/Slim/App.php(392): Slim\App->callMiddlewareStack
#54 /var/directus/vendor/slim/slim/Slim/App.php(297): Slim\App->process
#55 /var/directus/src/core/Directus/Application/Application.php(161): Slim\App->run
#56 /var/directus/public/index.php(5): Directus\Application\Application->run [] []
``` 
I notice the `Out of range value for column 'actuals_usd_period__ex_admin'` message and checked our database schema directly:
<img width="419" alt="Screenshot 2020-04-21 at 12 22 16" src="https://user-images.githubusercontent.com/15915453/79878676-fd658c80-83ed-11ea-9308-b4682e1cb390.png">
As you can see the field in question, `actuals_usd_period__ex_admin` is at `10,0` length.

Any assistance or advice on how to get around this error would be appreciated!

**Comment by shinroo** [comment]
The issue was that I had data in the field in question which was too large for the operation in quesiton.

**Comment by rijkvanzanten** [comment]
I'm going to move this over to the API repo so we can add in a proper error message for this 👍
