### ISSUE TITLE
Issue with installing directus. Loaded via SSL, due to "couldn't connect to api" error.

### ISSUE THREAD

**Issue by JayMcConnon** [directus/app#2851]
• Version of Directus - latest, pulled last night
• Server, OS & Database Details - amazon ec2 ubuntu 18.04 instance
Latest mysql php and apache2
• Error Messages -
``` [2020-05-31 21:22:43] api[].ERROR: Directus\Exception\InvalidDatabaseConnectionException: Invalid database connection in /var/www/directus/src/core/Directus/Services/ProjectService.php:107
Stack trace:
#0 /var/www/directus/src/endpoints/ProjectsCreate.php(17): Directus\Services\ProjectService->create
#1 [internal function]: Directus\Api\Routes\ProjectsCreate->__invoke
#2 /var/www/directus/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(40): call_user_func
#3 /var/www/directus/vendor/slim/slim/Slim/Route.php(281): Slim\Handlers\Strategies\RequestResponse->__invoke
#4 /var/www/directus/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\Route->__invoke
#5 /var/www/directus/vendor/slim/slim/Slim/Route.php(268): Slim\Route->callMiddlewareStack
#6 /var/www/directus/vendor/slim/slim/Slim/App.php(503): Slim\Route->run
#7 /var/www/directus/src/core/Directus/Application/Http/Middleware/CorsMiddleware.php(71): Slim\App->__invoke
#8 [internal function]: Directus\Application\Http\Middleware\CorsMiddleware->__invoke
#9 /var/www/directus/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array
#10 [internal function]: Slim\DeferredCallable->__invoke
#11 /var/www/directus/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#12 /var/www/directus/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\App->Slim\{closure}
#13 /var/www/directus/vendor/slim/slim/Slim/App.php(392): Slim\App->callMiddlewareStack
#14 /var/www/directus/vendor/slim/slim/Slim/App.php(297): Slim\App->process
#15 /var/www/directus/src/core/Directus/Application/Application.php(161): Slim\App->run
#16 /var/www/directus/public/index.php(5): Directus\Application\Application->run [] []
```

• Steps to Reproduce- - installed via git. enabled ssl certificate as per suggestion on 
• Relevant Info, Screenshots, Schema & Logs
![Screenshot 2020-06-01 at 12 21 14](https://user-images.githubusercontent.com/10206764/83404399-81099480-a402-11ea-9914-ec3dc6f25bc5.png)
I am struggling with directus. Loading the page on http loads the login page but get error "Cannot connect to API" when trying to login. I found another issue elsewhere on here that referenced needing the site running on SSL, so have set that up. 

Now when going to the page on https:// i get a spinner on load and no login page is presented. 

Have found the stack trace from questionaire in the error log. 

I also get this in the console when trying to load the page

I can ping /server/ping via http but not https://

**Comment by JayMcConnon** [comment]
Ok so i have fixed the error and i thought i would share what i found with it.

due to directus now needing an SSL certificate to work, i was getting a "could not connect to API" error on login when running on http.

I installed a lets encrypt certificate which then led to me having this problem where by i couldn't get the login page to load up.

I ran the tests for mod_rewrite using `apachectl -M | grep 'rewrite'` and it told me that there was an error loading my lets encrypt certificate. 
I checked it was there, and that open ssl could read it with `openssl x509 -text -noout -in /etc/letsencrypt/live/mysite.com/fullchain.pem`

It was showing not able to read it. I CHMOD'ed the folder to 755 but no joy. Googling it a bit more, the required permissions had to be applied to the `/etc/letsencrypt/archive` folder

Once i had sorted that out and added the same Allow override in my SSL virtual host, it was able to load the login page

As mentioned, i know this issue is not strictly related to directus, but also to just configuring SSL certificate in general, but as the package now requires SSL to work, i think it would help to perhaps add a bit more depth to the documentation regarding this. 


Thanks
