### ISSUE TITLE
direct us is giving unauthorised error for every user as well as for admin also.

### ISSUE THREAD

**Issue by thakurPooja2494** [directus/app#2874]
Hi team,
i am getting unauthorised error for direct us this was happend before 1 week also than i have reinstalled the direct us and again m facing the same issue. 
After using for some time automatically direct us is giving unauthorised error for every user as well as for admin also.

can you please help me out.
![Image 15-06-20 at 11 19 AM](https://user-images.githubusercontent.com/64476559/84622339-5f2c0980-aefa-11ea-8430-fe38ec521261.jpg)

**Comment by benhaynes** [comment]
Likely due to the recent updates browsers have been making to require HTTPS. Can you ensure that you are using SSL for this? (even if it's a local env)

**Comment by thakurPooja2494** [comment]
yes we are using ssl

**Comment by thakurPooja2494** [comment]
@benhaynes  
can you please help me out why again and again m getting 401 unauthorised error.. after enabling the https and ssl
![image (3)](https://user-images.githubusercontent.com/64476559/87011866-1bb97800-c1e6-11ea-9ede-7e84b743794f.png)

**Comment by thakurPooja2494** [comment]
@benhaynes  adding the logs

[2020-07-09 09:05:53] api[release_comm_v2].ERROR: Failed generating the SQL query. [] []
[2020-07-09 09:05:54] api[release_comm_v2].ERROR: Directus\Exception\UnauthorizedException: Unauthorized request in /var/www/directus/src/core/Directus/Services/UsersService.php:152
Stack trace:
#0 /var/www/directus/src/endpoints/Users.php(92): Directus\Services\UsersService->findByIds
#1 [internal function]: Directus\Api\Routes\Users->read
#2 /var/www/directus/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(40): call_user_func
#3 /var/www/directus/vendor/slim/slim/Slim/Route.php(281): Slim\Handlers\Strategies\RequestResponse->__invoke
#4 /var/www/directus/src/core/Directus/Application/Http/Middleware/AbstractRateLimitMiddleware.php(34): Slim\Route->__invoke
#5 [internal function]: Directus\Application\Http\Middleware\AbstractRateLimitMiddleware->__invoke
#6 /var/www/directus/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array
#7 [internal function]: Slim\DeferredCallable->__invoke
#8 /var/www/directus/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#9 /var/www/directus/src/core/Directus/Application/Http/Middleware/AuthenticationMiddleware.php(124): Slim\Route->Slim\{closure}
#10 [internal function]: Directus\Application\Http\Middleware\AuthenticationMiddleware->__invoke
#11 /var/www/directus/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array
#12 [internal function]: Slim\DeferredCallable->__invoke
#13 /var/www/directus/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#14 /var/www/directus/src/core/Directus/Application/Http/Middleware/TableGatewayMiddleware.php(25): Slim\Route->Slim\{closure}
#15 [internal function]: Directus\Application\Http\Middleware\TableGatewayMiddleware->__invoke
#16 /var/www/directus/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array
#17 [internal function]: Slim\DeferredCallable->__invoke
#18 /var/www/directus/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#19 /var/www/directus/src/core/Directus/Application/Http/Middleware/DatabaseMigrationMiddleware.php(15): Slim\Route->Slim\{closure}
#20 [internal function]: Directus\Application\Http\Middleware\DatabaseMigrationMiddleware->__invoke
#21 /var/www/directus/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array
#22 [internal function]: Slim\DeferredCallable->__invoke
#23 /var/www/directus/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#24 /var/www/directus/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\Route->Slim\{closure}
#25 /var/www/directus/vendor/slim/slim/Slim/Route.php(268): Slim\Route->callMiddlewareStack
#26 /var/www/directus/vendor/slim/slim/Slim/App.php(503): Slim\Route->run
#27 /var/www/directus/src/core/Directus/Application/Http/Middleware/AbstractRateLimitMiddleware.php(34): Slim\App->__invoke
#28 [internal function]: Directus\Application\Http\Middleware\AbstractRateLimitMiddleware->__invoke
#29 /var/www/directus/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array
#30 [internal function]: Slim\DeferredCallable->__invoke
#31 /var/www/directus/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#32 /var/www/directus/vendor/directus/proxy-detection/src/ProxyDetectionMiddleware.php(30): Slim\App->Slim\{closure}
#33 /var/www/directus/src/core/Directus/Application/Http/Middleware/ProxyMiddleware.php(18): RKA\Middleware\ProxyDetectionMiddleware->__invoke
#34 [internal function]: Directus\Application\Http\Middleware\ProxyMiddleware->__invoke
#35 /var/www/directus/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array
#36 [internal function]: Slim\DeferredCallable->__invoke
#37 /var/www/directus/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#38 /var/www/directus/vendor/akrabat/ip-address-middleware/src/IpAddress.php(113): Slim\App->Slim\{closure}
#39 [internal function]: RKA\Middleware\IpAddress->__invoke
#40 /var/www/directus/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array
#41 [internal function]: Slim\DeferredCallable->__invoke
#42 /var/www/directus/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#43 /var/www/directus/src/core/Directus/Application/Http/Middleware/CorsMiddleware.php(71): Slim\App->Slim\{closure}
#44 [internal function]: Directus\Application\Http\Middleware\CorsMiddleware->__invoke
#45 /var/www/directus/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array
#46 [internal function]: Slim\DeferredCallable->__invoke
#47 /var/www/directus/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#48 /var/www/directus/src/core/Directus/Application/Http/Middleware/ResponseCacheMiddleware.php(62): Slim\App->Slim\{closure}
#49 [internal function]: Directus\Application\Http\Middleware\ResponseCacheMiddleware->__invoke
#50 /var/www/directus/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array
#51 [internal function]: Slim\DeferredCallable->__invoke
#52 /var/www/directus/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#53 /var/www/directus/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\App->Slim\{closure}
#54 /var/www/directus/vendor/slim/slim/Slim/App.php(392): Slim\App->callMiddlewareStack
#55 /var/www/directus/vendor/slim/slim/Slim/App.php(297): Slim\App->process
#56 /var/www/directus/src/core/Directus/Application/Application.php(161): Slim\App->run
#57 /var/www/directus/public/index.php(5): Directus\Application\Application->run [] []
