### ISSUE TITLE
Interface: Time – leading zeros

### ISSUE THREAD

**Issue by benhaynes** [directus/app#824]
`15:03` is displayed as `15:3`... we need to pad the minutes

**Comment by segunolalive** [comment]
@benhaynes I've dug through the code. Can't find where the date-time formatting is being.

Could you give me some pointers here or is it being formatted from the API?

**Comment by benhaynes** [comment]
Sure! The `time` interface is located here:

https://github.com/directus/api/tree/master/extensions/core/interfaces/time

**Comment by segunolalive** [comment]
Thanks Ben.

**Comment by benhaynes** [comment]
Hey @segunolalive – could you describe the errors you're getting? Screenshots, details on your server, etc. If you submit a ticket we will figure it out and/or add info to the Docs to help!

Did you follow these steps?

https://docs.directus.io/api/contributor-guide/install-dev.html

**Comment by segunolalive** [comment]
I have it running now. This is what I was experiencing:

Running `npm run dev` in the extensions directory throws the following error:

`  /Users/andeladeveloper/codeSpace/directus/api/extensions/core/interfaces/div
ider/display.vue: Cannot read property 'walk' of null
    at HTMLAsset.generate (/Users/andeladeveloper/codeSpace/directus/api/extensions/node_modules/parcel/src/assets/HTMLAsset.js:193:14)
    at HTMLAsset.process (/Users/andeladeveloper/codeSpace/directus/api/extensions/node_modules/parcel/src/Asset.js:208:35)
    at <anonymous>`

**Reason:**
`extensions/core/interfaces/divider/display.vue` contains an just empty `template` tag

**Fix:** added an empty `div` and the error stopped.

Also, I tried to run the `api` directly in the browser and got the following error:
`{"error":{"code":3,"message":"Only Admin can see this information","class":"Directus\\Exception\\UnauthorizedException","file":"\/var\/www\/html\/src\/core\/Directus\/Services\/ServerService.php","line":20}}`

**Reason:**
I didn't realise I had to connect the App to the API in order to access the UI (silly).

**Comment by rijkvanzanten** [comment]
@benhaynes That particular issue was fixed in https://github.com/directus/api/commit/9e1e068104f44ca106fa77f0bc216bb173ac3482#diff-474563925299286795899bf2a8f85ceaR2

**Comment by segunolalive** [comment]
Noted @rijkvanzanten 

@benhaynes I can't seem to reproduce this issue.
